<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-D2GVCL39" name="KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG" tests="2" failures="2" timestamp="2021-10-11T20:15:16 IST" time="0.023" errors="0">
  <testcase name="B" time="0.005" classname="KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [null] but found [org.testng.asserts.SoftAssert@2de671dd]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [null] but found [org.testng.asserts.SoftAssert@2de671dd]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG.B(SoftAssertsInTestNG.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- B -->
  <system-out/>
  <testcase name="A" time="0.018" classname="KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expecting elementy to be visible expected [true] but found [false],
	Message is not displayed properly expected [Hello] but found [Hi]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expecting elementy to be visible expected [true] but found [false],
Message is not displayed properly expected [Hello] but found [Hi]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG.A(SoftAssertsInTestNG.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- A -->
  <system-out/>
</testsuite> <!-- KTCTC.JuneMavenProjectAutomation.SoftAssertsInTestNG -->
